stages:
  - build

variables:
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/ci-dind
  CONTAINER_TAG: ${CI_COMMIT_TAG}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
  CONTAINER_IMAGE_AARCH64: ${CONTAINER_IMAGE}:aarch64
  CONTAINER_IMAGE_AARCH64_TAGGED: ${CONTAINER_IMAGE}:aarch64-${CONTAINER_TAG}

# The image uses itself to build itself
image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind

build:
  stage: build
  only:
    - tags
  tags:
    - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

build-aarch64:
  stage: build
  only:
    - tags
  tags:
    - aarch64
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${CONTAINER_IMAGE_AARCH64} -f Dockerfile_aarch64 .
    - docker tag ${CONTAINER_IMAGE_AARCH64} ${CONTAINER_IMAGE_AARCH64_TAGGED}
    - docker push ${CONTAINER_IMAGE_AARCH64}
    - docker push ${CONTAINER_IMAGE_AARCH64_TAGGED}
