FROM docker:19.03.12-dind

# AWS CLI (Currently not working on ARCH64)
# ENV GLIBC_VER=2.34-r0
# RUN apk --update-cache add \
#         binutils \
#         curl \
#         groff \
#         bash \
#     && sed -i 's/ash/bash/g' /etc/passwd \
#     && curl -sL https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -o /etc/apk/keys/sgerrand.rsa.pub \
#     && curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VER}/glibc-${GLIBC_VER}.apk \
#     && curl -sLO https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VER}/glibc-bin-${GLIBC_VER}.apk \
#     && apk del libc6-compat \
#     && apk add \
#         glibc-${GLIBC_VER}.apk \
#         glibc-bin-${GLIBC_VER}.apk \
#     && curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip \
#     && unzip -q awscliv2.zip \
#     && aws/install \
#     && rm -rf \
#         awscliv2.zip \
#         aws \
#         /usr/local/aws-cli/v2/*/dist/aws_completer \
#         /usr/local/aws-cli/v2/*/dist/awscli/data/ac.index \
#         /usr/local/aws-cli/v2/*/dist/awscli/examples \
#     && apk --no-cache del \
#         binutils \
#         curl \
#     && rm glibc-${GLIBC_VER}.apk \
#     && rm glibc-bin-${GLIBC_VER}.apk \
#     && rm -rf /var/cache/apk/* \
#     && docker --version \
#     && aws --version



# Kubectl
ENV KUBE_LATEST_VERSION="v1.23.1"
RUN apk add --update ca-certificates \
 && apk add -t deps \
 && apk add --update curl \
 && export ARCH="$(uname -m)" && if [[ ${ARCH} == "x86_64" ]]; then export ARCH="amd64"; elif [[ ${ARCH} == "aarch64" ]]; then export ARCH="arm64"; fi && curl -L https://dl.k8s.io/release/${KUBE_LATEST_VERSION}/bin/linux/${ARCH}/kubectl -o /usr/local/bin/kubectl \
 && chmod +x /usr/local/bin/kubectl \
 && apk del --purge deps \
 && rm /var/cache/apk/*

# envsubts
RUN apk add gettext
